// Canonical alias map used by the importer.
// File types (adjust to real set used in the project)
export type FileType =
  | 'CLIENTES'
  | 'VENDEDORES'
  | 'PRODUTOS'
  | 'MOVIMENTACOES'
  | 'ESTOQUE';

export const NORMALIZE_HEADER = (h: string) =>
  h?.toString()
    .replace(/^\uFEFF/, '') // strip BOM
    .normalize('NFD').replace(/[\u0300-\u036f]/g, '') // remove accents
    .toLowerCase()
    .trim()
    .replace(/[^\w]+/g, '_'); // spaces/punct → underscore

// Map normalized incoming header → canonical field
export const HEADER_ALIAS_MAP: Record<FileType, Record<string, string>> = {
  CLIENTES: {
    codigo: 'codigo_cliente',
    codigo_cliente: 'codigo_cliente',
    codigo_do_cliente: 'codigo_cliente',
    cod_cliente: 'codigo_cliente',
    idcliente: 'codigo_cliente',
    codigocliente: 'codigo_cliente',
    nome: 'nome',
    nome_do_cliente: 'nome',
    razao_social: 'nome',
    cliente: 'nome',
    cnpj: 'cnpj',
    cnpj_cliente: 'cnpj',
    cnpj_do_cliente: 'cnpj',
    documento: 'cnpj',
    endereco: 'endereco',
    endereco_: 'endereco',
    logradouro: 'endereco',
    rua: 'endereco',
    bairro: 'bairro',
    municipio: 'municipio',
    municipio_cliente: 'municipio',
    municipio_: 'municipio',
    cidade: 'municipio',
    estado: 'estado',
    uf: 'estado',
    cep: 'cep',
    email: 'email',
    e_mail: 'email',
    telefone: 'telefone',
    fone: 'telefone',
    celular: 'telefone',
    inscricao_estadual: 'inscricao_estadual',
    inscricao_estadual_: 'inscricao_estadual',
    ie: 'inscricao_estadual',
    tipo: 'tipo_cliente',
    tipo_cliente: 'tipo_cliente',
    segmento: 'tipo_cliente',
  },
  VENDEDORES: {
    codigo: 'codigo_vendedor',
    codigo_vendedor: 'codigo_vendedor',
    cod_vendedor: 'codigo_vendedor',
    idvendedor: 'codigo_vendedor',
    codigo_do_vendedor: 'codigo_vendedor',
    nome: 'nome',
    nome_vendedor: 'nome',
    vendedor: 'nome',
    ativo: 'ativo',
    status: 'ativo',
    habilitado: 'ativo',
  },
  PRODUTOS: {
    codigo: 'codigo_produto',
    codigo_produto: 'codigo_produto',
    cod_produto: 'codigo_produto',
    sku: 'codigo_produto',
    idproduto: 'codigo_produto',
    produto_codigo: 'codigo_produto',
    descricao: 'descricao',
    descricao_: 'descricao',
    descricao_produto: 'descricao',
    nome: 'descricao',
    produto: 'descricao',
    produto_nome: 'descricao',
  },
  MOVIMENTACOES: {
    distribuidor: 'distribuidor',
    nome_distribuidor: 'distribuidor',
    revenda: 'distribuidor',
    cnpj_distribuidor: 'cnpj_distribuidor',
    cnpj_distribuidor_: 'cnpj_distribuidor',
    cnpj_revenda: 'cnpj_distribuidor',
    codigo_vendedor: 'codigo_vendedor',
    cod_vendedor: 'codigo_vendedor',
    vendedor: 'codigo_vendedor',
    codigo_vendedor_: 'codigo_vendedor',
    codigo_vendedor_do_pedido: 'codigo_vendedor',
    nome_vendedor: 'nome_vendedor',
    vendedor_nome: 'nome_vendedor',
    nome_do_vendedor: 'nome_vendedor',
    codigo_cliente: 'codigo_cliente',
    cod_cliente: 'codigo_cliente',
    cliente: 'codigo_cliente',
    codigo_do_cliente: 'codigo_cliente',
    idcliente: 'codigo_cliente',
    nome_cliente: 'nome_cliente',
    cliente_nome: 'nome_cliente',
    nome_do_cliente: 'nome_cliente',
    codigo_produto: 'codigo_produto',
    cod_produto: 'codigo_produto',
    produto: 'codigo_produto',
    sku: 'codigo_produto',
    idproduto: 'codigo_produto',
    nome_produto: 'nome_produto',
    descricao_produto: 'nome_produto',
    produto_nome: 'nome_produto',
    quantidade: 'quantidade',
    qtd: 'quantidade',
    qtde: 'quantidade',
    quant: 'quantidade',
    volume: 'quantidade',
    valor_total: 'valor_total',
    valor: 'valor_total',
    valor_total_: 'valor_total',
    valor_total_liquido: 'valor_total',
    valor_venda: 'valor_total',
    valor_liquido: 'valor_total',
    data: 'data',
    data_pedido: 'data',
    data_venda: 'data',
    data_emissao: 'data',
    emissao: 'data',
    numero_nota: 'numero_nota',
    nota: 'numero_nota',
    nf: 'numero_nota',
    numero_nf: 'numero_nota',
    nota_fiscal: 'numero_nota',
    tipo_saida: 'tipo_saida',
    tipo: 'tipo_saida',
    natureza: 'tipo_saida',
    tipo_saida_produto: 'tipo_saida',
    descricao_saida: 'descricao_saida',
    descricao: 'descricao_saida',
    descricao_saida_produto: 'descricao_saida',
    tabela_precos: 'tabela_precos',
    tabela: 'tabela_precos',
    tabela_preco: 'tabela_precos',
    venda_com_qr_code: 'venda_com_qr_code',
    qr_code: 'venda_com_qr_code',
    venda_qr_code: 'venda_com_qr_code',
    qr: 'venda_com_qr_code',
  },
  ESTOQUE: {
    distribuidor: 'distribuidor',
    revenda: 'distribuidor',
    nome_distribuidor: 'distribuidor',
    codigo_produto: 'codigo_produto',
    cod_produto: 'codigo_produto',
    produto: 'codigo_produto',
    sku: 'codigo_produto',
    idproduto: 'codigo_produto',
    quantidade: 'quantidade',
    qtd: 'quantidade',
    qtde: 'quantidade',
    quant: 'quantidade',
    volume: 'quantidade',
    data_estoque: 'data_estoque',
    data: 'data_estoque',
    data_inventario: 'data_estoque',
    data_inventario_: 'data_estoque',
  },
};

export const REQUIRED_FIELDS: Record<FileType, string[]> = {
  CLIENTES: ['codigo_cliente', 'nome'],
  VENDEDORES: ['codigo_vendedor', 'nome'],
  PRODUTOS: ['codigo_produto', 'descricao'],
  MOVIMENTACOES: ['data', 'codigo_produto', 'codigo_cliente', 'quantidade'],
  ESTOQUE: ['codigo_produto', 'quantidade', 'data_estoque'],
};

export function canonicalizeHeader(file: FileType, raw: string): string | null {
  const norm = NORMALIZE_HEADER(raw);
  return HEADER_ALIAS_MAP[file]?.[norm] ?? null;
}
